### ISSUE TITLE
Support clusters with candidate OCP release

### ISSUE THREAD

**Issue by mgencur** [openshift-knative/hack#105]
The tooling currently generates jobs that use cluster pools. However, it might be required to test with a candidate release that was not included in cluster pools yet (like OCP 4.15 at the moment).
There should be an option to choose starting the cluster from scratch, together with an option to choose the exact release through the `release` stanza, e.g.:
```
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.15"
```
